### ISSUE TITLE
Moto g4 build prop error

### ISSUE THREAD

**Issue by vk496** [nneonneo/threes-ai#11]
Hi,

I have error with Moto G4 plus CM 14.1 (Android 7.1.1). When execute, the key **ro.product.model** doesnt exist. However, when use in terminal **adb shell getprop**, it exists

**Comment by nneonneo** [comment]
Hmm, perhaps they moved that key out of /system/build.prop. Can you list
the contents of that file on your device?

If it doesn't have the model key, I'll refactor the inputemu module to use
getprop rather than the props file.
