### ISSUE TITLE
can't run the manual assistent

### ISSUE THREAD

**Issue by Allysoldier** [nneonneo/threes-ai#5]
the error I am getting is:
Couldn't find threes library bin/threes.{so,dll,dylib}! Make sure to build it first.
![threes problem](https://cloud.githubusercontent.com/assets/12244459/7465868/41f1970a-f2d9-11e4-95fd-2017b3c453ba.png)

The other guy closes his issue without saying anything about it.

**Comment by nneonneo** [comment]
Follow the README to build it or get prebuilts.

Robert
