### ISSUE TITLE
Xbox One version bonus tile deck

### ISSUE THREAD

**Issue by tarragon** [nneonneo/threes-ai#9]
Howdy,

I've been trying this AI out on the Xbox One version of Threes! and inevitably run into the situation where the bonus tile given by the game isn't expected by the AI, causing me to reset the board.

This is mostly just inconvenient, but I do wonder if the AI might not be able to predict as well given it's obviously not expecting these particular bonus tiles.

Example from the manual assistant:

```
Move number 31
Previous move: right ; tile: 2
[[  0   3   3  48]
 [  0   1   3  48]
 [  0   0   6 192]
 [  2   0   6 384]]
Current score: 9261
Next tile: set([4, 5, 6]) (deck=1:2, 2:2, 3:3)
*** Suggested move: down

Current board or difference from last board?
2,48
Didn't understand your input: New tile wasn't in previous tile set
Current board or difference from last board?
```

This is running on OSX if that matters. I had a peek at the C++ code but my C++-fu isn't as good as my Ruby or Perl-fu, so it wasn't clear to me how the bonus deck is constructed.

Let me know if you need any further information.

**Comment by nneonneo** [comment]
Thanks for spotting this bug! The assistant indeed had the wrong bonus tileset calculation. And you are indeed correct - the AI would not have been expecting the extra tiles, which could adversely affect its performance.
